root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  build-your-rooms/build-your-rooms: build-your-rooms/README.md
  build-your-rooms/build-your-rooms/configure-live-view: build-your-rooms/configure-live-view.md
  build-your-rooms/build-your-rooms/add-puzzles-and-clues: build-your-rooms/add-puzzles-and-clues.md
  build-your-rooms/build-your-rooms/manage-room-media: build-your-rooms/manage-room-media.md
  run-live-sessions/run-rooms: run-a-session/README.md
  run-live-sessions/run-rooms/run-a-live-session: run-a-session/run-a-live-session.md
  run-rooms: run-a-session/README.md
  run-rooms/prepare-your-room-station: prepare-for-a-shift/prepare-your-room-station.md
  run-rooms/run-a-live-session: run-a-session/run-a-live-session.md
  run-rooms/troubleshoot-live-session-issues: run-a-session/troubleshoot-a-live-session.md
  review-performance: review-and-improve/README.md
  review-performance/review-performance: review-and-improve/README.md
  review-performance/view-room-statistics: review-and-improve/view-room-statistics.md
  review-performance/review-performance/view-room-statistics: review-and-improve/view-room-statistics.md
  account/account: account/README.md
  account/account/use-account-settings: account/use-account-settings.md
  get-help: help/README.md
